services:
  backend:
    build: ./backend
    container_name: auth-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=your-secret-key-change-in-production
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: auth-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
