apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: auth-app
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer  # Exposé publiquement pour être accessible depuis le navigateur
